### ISSUE TITLE
[BUG] App freezes on startup due to Objectbox exception

### ISSUE THREAD

**Issue by MatKershaw3708** [JaffaKetchup/flutter_map_tile_caching#168]
### What is the bug?

I am having issues relating to objectbox, this occurs on app startup and if freezes on the splash screen:

`
E/flutter (11974): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: failed to create store: Cannot open store: another store is still open using the same path: "/data/data/com.myappname.mobile/app_flutter/fmtc" (OBX_ERROR code 10001)
E/flutter (11974): #0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:74)
E/flutter (11974): #1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:54)
E/flutter (11974): #2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:31)
E/flutter (11974): #3      Store._checkStorePointer (package:objectbox/src/native/store.dart:451)
E/flutter (11974): #4      new Store (package:objectbox/src/native/store.dart:274)
E/flutter (11974): #5      openStore (package:flutter_map_tile_caching/src/backend/impls/objectbox/models/generated/objectbox.g.dart:270)
E/flutter (11974): <asynchronous suspension>
E/flutter (11974): #6      _worker (package:flutter_map_tile_caching/src/backend/impls/objectbox/backend/internal_workers/standard/worker.dart:34)
E/flutter (11974): <asynchronous suspension>
E/flutter (11974): `

### How can we reproduce it?

Issue occurs on Release builds only, and has only occurred since updating to API 34 as well as a new Gradle version.

### Platforms

Android API 34

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

**Comment by JaffaKetchup** [comment]
Does your app use a background task that stays running when the app is killed?

**Comment by MatKershaw3708** [comment]
It uses background GPS, but this needs to be manually started and the issue occurs even if the device has just been restarted.

**Comment by MatKershaw3708** [comment]
I've wrapped the initialiser in a try catch (as per the documentation https://fmtc.jaffaketchup.dev/general/initialisation) and it seems to resolve the issue.

Thanks for your help!
