### ISSUE TITLE
[BUG] Unsupported operation: Watching is not supported on the current platform

### ISSUE THREAD

**Issue by azataiot** [JaffaKetchup/flutter_map_tile_caching#59]
**Describe The Bug**
App crashes in first run on iOS. using the official example with all dependencies installed.

**Expected Behaviour**
App should run and (i do not know what is next, i just wanted to try out the package)

**Screenshots & Recordings**
```dart
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            5.4s
Debug service listening on ws://127.0.0.1:51342/bKfPVmvulqU=/ws
Syncing files to device iPhone 13...
../lib/src/internal/image_provider.dart:75:23: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
      PaintingBinding.instance?.imageCache?.evict(this);
                      ^
../lib/src/internal/image_provider.dart:88:27: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
          PaintingBinding.instance?.imageCache?.evict(this);
                          ^
../lib/src/internal/image_provider.dart:98:27: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
          PaintingBinding.instance?.imageCache?.evict(this);
                          ^
../lib/src/internal/image_provider.dart:140:23: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
      PaintingBinding.instance?.imageCache?.evict(this);
                      ^
lib/pages/store_manager/store_manager.dart:124:55: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/painting/binding.dart').
                                      PaintingBinding.instance?.imageCache
                                                      ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/feature_discovery-0.14.1/lib/src/widgets/layout.dart:92:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/feature_discovery-0.14.1/lib/src/widgets/layout.dart:112:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/backdrop-0.7.2/lib/src/scaffold.dart:713:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((_) => _notify());
                     ^
../../../SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/backdrop-0.7.2/lib/src/scaffold.dart:716:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../SDKs/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) => _notify());
                         ^

======== Exception caught by widgets library =======================================================
The following UnsupportedError was thrown building Consumer<GeneralProvider>(dirty, dependencies: [_InheritedProviderScope<GeneralProvider?>]):
Unsupported operation: Watching is not supported on the current platform

The relevant error-causing widget was: 
  Consumer<GeneralProvider> Consumer:file:///Users/azat/Developer/Flutter/flutter_map_tile_caching/example/lib/pages/home/components/panel/panel.dart:26:16
When the exception was thrown, this was the stack: 
#0      MapCachingManager.watchStoreChanges (package:flutter_map_tile_caching/src/storage_managers/storage_manager.dart:201:7)
#1      Panel.build.<anonymous closure> (package:fmtc_example/pages/home/components/panel/panel.dart:32:27)
#2      Consumer.buildWithChild (package:provider/src/consumer.dart:179:19)
#3      SingleChildStatelessWidget.build (package:nested/nested.dart:259:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#5      SingleChildStatelessElement.build (package:nested/nested.dart:279:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#10     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (51 frames)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#62     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#63     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (9 frames)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#77     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#78     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#79     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#80     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#81     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#82     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#86     _invoke (dart:ui/hooks.dart:151:10)
#87     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#88     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

**Additional Information**
Add any other context about the problem here, or remove this section.

I think we need to implement some platform-aware methods for platform specific cases.

---

**Doctors Report**

```shell
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**To Reproduce**
Steps to reproduce the behaviour:

Just build the project and launch it on iOS

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [x] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

**Comment by azataiot** [comment]
Just run the app on Android, it also failed for some null safety check rules.

**Comment by JaffaKetchup** [comment]
Hi there @azataiot,
The issues you mentioned should be solved by using the pre-release version v5 available on pub.dev.
Please try this, and let me know if it works.
Thanks.

**Comment by azataiot** [comment]
> Hi there @azataiot, The issues you mentioned should be solved by using the pre-release version v5 available on pub.dev. Please try this, and let me know if it works. Thanks.

v5 did not work, i think there are many API changes in V5. 

Also I updated all the dependencies to the latest version.

Here are common problems:

``` bash
Undefined class 'MapCachingManager'.
Undefined class 'RegionMode'. 
Undefined name 'StorageCachingTileProvider'.
Undefined class 'StorageCachingTileProvider'.
...
```
and more.

I think they are due to the API changes in various packages.

**Comment by JaffaKetchup** [comment]
Unfortunately, v5 has many breaking changes, and you will need to migrate any existing code. The examples on the main branch no longer apply.

Due to these issues being fixed in v5, I'm going to close this issue.

**Comment by JaffaKetchup** [comment]
Re-opened, as this is now an issue again. A workaround fix is in progress, but also note https://github.com/dart-lang/sdk/issues/51549.
